name: Go CI

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Print Go env
        run: go env

      - name: Download deps
        run: go mod download

      - name: Vet
        run: go vet ./...

      - name: Build all packages
        run: go build ./...

      - name: Run tests
        env:
          CGO_ENABLED: 1
        run: |
          # Adjust flags to your needs (race requires CGO)
          go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Build CLI binary artifact
        run: |
          mkdir -p build
          go build -ldflags "-s -w" -o build/salary-bot ./cmd/main.go

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: salary-bot_linux_amd64
          path: build/salary-bot

  # Optional release on tags. Uncomment and configure if needed.
  # release:
  #   name: Release (tag)
  #   if: startsWith(github.ref, 'refs/tags/')
  #   runs-on: ubuntu-latest
  #   needs: [ build-test ]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Go
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: '1.22.x'
  #         cache: true
  #
  #     - name: Build release binaries (Linux/macOS)
  #       run: |
  #         mkdir -p dist
  #         GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o dist/salary-bot_linux_amd64 ./cmd/main.go
  #         GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o dist/salary-bot_darwin_amd64 ./cmd/main.go
  #         GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o dist/salary-bot_darwin_arm64 ./cmd/main.go
  #
  #     - name: Upload release artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: salary-bot_release_binaries
  #         path: dist/*
